### ISSUE TITLE
Code_Bug?

### ISSUE THREAD

**Issue by ryrl9703** [XWangLabTHU/ARIC#1]
---------------------------------------------
--------------WELCOME TO ARIC----------------
---------------------------------------------
Data reading finished!
ARIC Engines Start, Please Wait......
Traceback (most recent call last):
  File "/home/pcwang/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-996cca571e9f>", line 1, in <module>
    runfile('/mnt/data/pcwang/Python/Study/ARIC/test.py', wdir='/mnt/data/pcwang/Python/Study/ARIC')
  File "/home/pcwang/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/pcwang/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/data/pcwang/Python/Study/ARIC/test.py", line 11, in <module>
    ARIC(mix_path=path_mix,ref_path=path_ref)
  File "/home/pcwang/anaconda3/lib/python3.8/site-packages/ARIC/deconvolution.py", line 99, in ARIC
    tmppath=tmppath,
UnboundLocalError: local variable 'tmppath' referenced before assignment

How should I solve this problem?

**Comment by Honchkrow** [comment]
Hi @ryrl9703 ,
    Sorry for the late response.
    We just update the functions to output the markers selected for each sample. Markers will be saved in "tmppath". The error was caused by the default "tmppath" value, now it has been fixed.
    Thank you again for report the bug! 
    If you have any other questions, please let me know and I will try my best to help you.

Shaway
